name: x86_64-pc-linux-gnu.yml
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libgtk-3-0 ninja-build libgtk-3-dev libnotify-bin libnotify-dev
    
    - name: Configure CMake
      run: mkdir build && cd build/; cmake .. -DNVD_USE_GTK4=OFF -DNVD_BUILD_STATIC=OFF -DNVDIALOG_MAXBUF=4096 -G "Ninja" -DWIN32_TARGET=OFF -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Install library
      run: sudo cmake --install ${{github.workspace}}/build/
    - name: Test
      # GitHub CI does not provide any X server to perform the testing to, so we will ignore failures.
      run: cd ${{github.workspace}}/build/ && ctest --output-on-failure || cat ${{github.workspace}}/build/Testing/Temporary/LastTest.log
